name: Deploy to GCP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'
        required: true
        default: 'prod'
#  push: 
#    branches: [ main ]
  

env:
  PROJECT: contract-reader
  BRANCH: main
  SERVICE: contract-reader
  IMAGE: contract-reader-image

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: $BRANCH

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: contract-reader

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
        
   
    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT/$IMAGE:$GITHUB_SHA"
        
    # Deploy the image to Google Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE --region europe-west4 --project contract-reader --image gcr.io/$PROJECT/$IMAGE:$GITHUB_SHA --platform managed

