name: DEV - deploy

on: [workflow_dispatch]

env: 
  TF_IN_AUTOMATION: true 
  TF_WORKSPACE: gcp-contractreader-ui-dev

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploy Contracts Hub UI to GCP
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/build-docker-deploy-to-gcp
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BRANCH: dev
          SERVICE: contract-reader-ui-service-tfd-dev
          IMAGE: contract-reader-ui-image-dev
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          ENGINE-ENDPOINT: https://dev.api.contracthub.thinktalkbuild.com
          OAUTH_GOOGLE_SECRET: ${{ secrets.OAUTH_GOOGLE_SECRET }}