name: Deploy to GCP - DEV-DAVE

on: [workflow_dispatch]

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploy to dev/dave environment
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/build-docker-deploy-to-gcp
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BRANCH: devenv/dave
          SERVICE: contract-reader-devenv-dave
          IMAGE: contract-reader-image-devenv-dave