name: Deploy Contracts Hub UI to Prod

on: [workflow_dispatch]

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploy Contracts Hub UI to GCP
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/build-docker-deploy-to-gcp
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BRANCH: main
          SERVICE: contract-reader-ui-service-tfd
          IMAGE: contract-reader-ui-image
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          ENGINE-ENDPOINT: https://contract-reader-engine-service-tfd-sm43mbtjmq-ez.a.run.app
          TFCLOUD-WORKSPACE: gcp-contractreader-ui