name: Deploy to GCP - PROD

on: [workflow_dispatch]

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/build-docker-deploy-to-gcp
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}